### ISSUE TITLE
As a person in need, I to tap the hotline button so that I can talk to someone

### ISSUE THREAD

**Issue by spittaro17** [cse442-spring-2020-offering/cse442-semester-project-pixar-s-i#15]

**Comment by rex-ix** [comment]
Acceptance Tests:
1. Open the app and log in, which will navigate to the main screen
2. On the list of buttons on the main screen, tap the button labeled 'Talk'
3. Once this is done, a screen will pop up which has two buttons "dial" and "back" in the middle.
4. When clicking the "dial" button, a request will show up to ask permission to use the phone. After click "allow", the app will call someone provided by the user.

**Comment by rex-ix** [comment]
Acceptance Tests:
1. Open the app and log in, which will navigate to the main screen
2. On the list of buttons on the main screen, tap the button labeled 'Talk'
3. Once this is done, a screen will pop up which has two buttons "dial" and "back" in the middle.
4. When clicking the "dial" button, a request will show up to ask permission to use the phone. After click "allow", the app will call someone provided by the user.
