### ISSUE TITLE
As someone seeking motivation, I want to click to motivation button, so I can be sent to a chat menu

### ISSUE THREAD

**Issue by spittaro17** [cse442-spring-2020-offering/cse442-semester-project-pixar-s-i#19]

**Comment by rex-ix** [comment]
1. Open the app and log in, which will navigate to the main screen.
2. On the list of buttons on the main screen, tap the button labeled 'Motivation'.
3. Once this is done, a screen will pop up with two buttons 'search' and "accept" in the middle.
4. Tap the "search" button and a new screen that contains the top five volunteers will pop up. 
5. Click a random volunteer, which will navigate to the chat screen. Then the user can chat with the volunteer.
