### ISSUE TITLE
As a student returning to the app, I want to login to my profile, so that I can view my profile page

### ISSUE THREAD

**Issue by spittaro17** [cse442-spring-2020-offering/cse442-semester-project-pixar-s-i#30]
Acceptance Test:

Script 1: 1) User enters in Email
2) User enters password
3) Presses Submit Button
4) Switches over to the main page
5) On Main Page user click profile button to reach the profile page.

Script 2: 1) User presses sign up button
2) Transfers to the sign up page
3) After signup is completed transfers user to the main page
4) User uses the profile button to change over to the profile page

**Comment by rgroesbeck09** [comment]
Acceptance Test: 

Script 1: User enters in Email
             User enters password
             Presses Submit Button
             Switches over to the main page

Script 2: User presses sign up button
             Transfers to the sign up page
