### ISSUE TITLE
As a person wanting to change their settings, I want to click on the settings button, so that I can go to the settings page

### ISSUE THREAD

**Issue by spittaro17** [cse442-spring-2020-offering/cse442-semester-project-pixar-s-i#48]
Acceptance Test:
1. The user opens the app and ships login which will navigate to the main screen.
2. On the list of buttons on the main screen, tap the button labeled 'Settings'.
3. After tapping the button, a screen will pop up with the label "Settings" at the top.
4. In the settings page, there are two buttons "Notifications" and "History". Also, there is one switch that contains a message "Volunteer".

**Comment by rex-ix** [comment]
Acceptance Test:
1. The user opens the app and ships login which will navigate to the main screen.
2. On the list of buttons on the main screen, tap the button labeled 'Settings'.
3. After tapping the button, a screen will pop up with the label "Settings" at the top.
4. In the settings page, there are two buttons "Notifications" and "History". Also, there is one switch that contains a message "Volunteer".
