### ISSUE TITLE
As an early sleeper, I want to receive notifications to a certain time, so my beauty sleep does not get disturbed.

### ISSUE THREAD

**Issue by rgroesbeck09** [cse442-spring-2020-offering/cse442-semester-project-pixar-s-i#8]
Acceptance Test:

**Comment by rex-ix** [comment]
Acceptance Tests:
1. Open the app and log in, which will navigate to the main screen
2. On the list of buttons on the main screen, tap the button labeled 'profile'.
3. Once this is done, a screen will pop up with the label 'Settings' at the bottom
4. Tap the "Settings" button to go into the "Settings" screen.
5. Tap the "Notifications" button to go into the "Notifications" screen.
6. In the "Notifications" screen, the user can either select turn off all notifications or go into a certain activity and turn off the notification for that activity.
7. \Tap each button to go into a specific feature's notification and there are a switch bar and a date dialog for users to choose to turn off notifications forever or in a certain time.
